import { useState } from 'react'
import './App.css'

function App() {
  const [activeProject, setActiveProject] = useState(0)
  const projects = [
    { number: '01', title: 'Post-Quantum Encryption Research', type: 'Texas A&M University · 2026-present', description: 'As an undergraduate research assistant at Texas A&M University, researching hybrid cryptosystems using lattice-based cryptography, Attribute-Based Encryption (ABE), and Identity-Based Encryption (IBE) to develop quantum-resistant systems.', impact: 'Quantum-resistant systems', stack: ['C++', 'Lattice cryptography', 'ABE / IBE'] },
    { number: '02', title: 'Dig ‘Em Aggies', type: 'Full-stack developer · 2025-present', description: 'Led development and deployment of digemaggies.org for organizational operations and outreach, building scalable architecture, dynamic UI components, and structured content systems.', impact: 'Production deployment', stack: ['JavaScript', 'HTML / CSS', 'Full-stack'] },
    { number: '03', title: 'Campus Climate Monitor', type: 'Embedded systems · 2023-2024', description: 'Deployed a real-time temperature and humidity monitoring system across five campuses, integrating sensors with embedded software for continuous environmental data collection.', impact: 'Thousands of dollars saved', stack: ['Embedded software', 'Sensors', 'Systems design'] },
  ]
  const experience = [
    { date: 'September 2026-now', title: 'Undergraduate Research Assistant', company: 'Post-Quantum Encryption · Texas A&M University', description: 'Researching hybrid cryptosystems using lattice-based cryptography, Attribute-Based Encryption (ABE), and Identity-Based Encryption (IBE) for quantum-resistant systems. Implementing and evaluating cryptographic algorithms in C++, analyzing performance, security, scalability, and resilience against quantum-based attacks.' },
    { date: '2025-26', title: 'Counselor / Projects / High-Risk Activity Guide', company: 'Pine Cove Shores · Flint, Texas', description: 'Led and mentored a group of eight high school students, supervised high-risk outdoor activities, and supported camp maintenance and project work while caring for more than $65,000 of equipment.' },
    { date: '2023-24', title: 'Student Intern', company: 'Celina Independent School District · Celina, Texas', description: 'Deployed a real-time temperature and humidity monitoring system across five campuses, integrating sensors with embedded software and enabling preventative maintenance.' },
    { date: '2022', title: 'Web Development Intern', company: 'Deep Space Robots · Dallas, Texas', description: 'Developed responsive front-end features for a web development company using HTML, CSS, and JavaScript, improving UI consistency and cross-browser compatibility through debugging and iteration.' },
  ]
  const currentProject = projects[activeProject]

  return (
    <main>
      <nav className="nav shell"><a className="wordmark" href="#top" aria-label="Josh Bennett home"><span>JB</span> / portfolio</a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a className="nav-contact" href="mailto:Jbbennettwork@gmail.com">Get in touch <span>↗</span></a></div></nav>
      <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">Cybersecurity · post-quantum research · Texas A&amp;M ’28</p><h1>I build systems<br /><em>ready for what’s next.</em></h1><p className="hero-intro">Electronic systems engineering student focused on cybersecurity, post-quantum cryptography, and reliable software that can stand up to real-world threats.</p><div className="hero-actions"><a className="button button-primary" href="#work">Explore my work <span>↓</span></a><a className="text-link" href="mailto:Jbbennettwork@gmail.com">Jbbennettwork@gmail.com <span>↗</span></a></div></div><div className="hero-visual" aria-label="Josh Bennett, cybersecurity and electronic systems engineering student"><div className="visual-grid"></div><div className="portrait-frame"><img src="/josh-bennett.jpg" alt="Josh Bennett in front of the United States Capitol" /></div><div className="visual-caption"><span>Currently</span><strong>Researching quantum-resistant<br />cryptographic systems.</strong></div><span className="orbit orbit-one"></span><span className="orbit orbit-two"></span></div></section>
      <div className="ticker"><div className="ticker-inner">CYBERSECURITY · POST-QUANTUM CRYPTOGRAPHY · SECURE SYSTEMS · SOFTWARE DEVELOPMENT <span>✳</span> CYBERSECURITY · POST-QUANTUM CRYPTOGRAPHY · SECURE SYSTEMS · SOFTWARE DEVELOPMENT <span>✳</span></div></div>
      <section className="section shell" id="work"><div className="section-heading"><p className="eyebrow">Selected work / 2022—present</p><h2>Security-minded<br /><em>systems in practice.</em></h2><p className="section-note">Research, software, and embedded systems shaped by reliability, security, and useful outcomes.</p></div><div className="project-layout"><div className="project-list">{projects.map((project, index) => <button className={`project-tab ${activeProject === index ? 'active' : ''}`} key={project.number} onClick={() => setActiveProject(index)}><span className="project-number">{project.number}</span><span><strong>{project.title}</strong><small>{project.type}</small></span><span className="tab-arrow">↗</span></button>)}</div><article className="project-detail"><div className="detail-top"><span>{currentProject.type}</span><span>{currentProject.number} / 03</span></div><div className="terminal-art"><div className="terminal-bar"><i></i><i></i><i></i><span>system / live</span></div><div className="terminal-lines"><p><b>01</b> <span>const</span> outcome = <em>"{currentProject.impact}"</em></p><p><b>02</b> <span>secure</span>(reliable, useful, effective)</p><p><b>03</b> <span className="lime">✓ ready for the next challenge</span></p></div></div><h3>{currentProject.title}</h3><p className="detail-description">{currentProject.description}</p><div className="stack-row">{currentProject.stack.map((item) => <span key={item}>{item}</span>)}</div></article></div></section>
      <section className="about-band" id="about"><div className="shell about-grid"><div><p className="eyebrow">The short version</p><h2>Security-minded.<br /><em>Systems curious.</em></h2></div><div className="about-copy"><p>I’m Josh, an Electronic Systems Engineering Technology student at Texas A&amp;M with a minor in Cybersecurity, graduating in May 2028. My current research focuses on hybrid cryptosystems and quantum-resistant encryption.</p><p>I like the space where security, software, hardware, and people overlap, from evaluating cryptographic algorithms in C++ to deploying production web systems and embedded monitoring.</p><a className="text-link light-link" href="mailto:Jbbennettwork@gmail.com">Let’s build something resilient <span>↗</span></a></div></div></section>
      <section className="section shell experience"><div className="section-heading compact"><p className="eyebrow">Experience / learning in public</p><h2>Where I’ve been useful.</h2></div><div className="timeline">{experience.map((item) => <div className="timeline-item" key={`${item.title}-${item.company}`}><span className="timeline-date">{item.date}</span><div><h3>{item.title} <small>{item.company}</small></h3><p>{item.description}</p></div></div>)}</div></section>
      <section className="service-band"><div className="shell service-grid"><div><p className="eyebrow">Beyond the build</p><h2>Leadership is<br /><em>part of the system.</em></h2></div><div className="service-list"><div><strong>Impact Retreat Leadership Team</strong><span>Texas A&amp;M University · Fall 2026-present</span><p>Helping plan and execute large-scale student events, coordinating logistics, mentoring students, teaching leadership principles, and facilitating group discussions.</p></div><div><strong>Leadership Team</strong><span>First Baptist Church · Spring 2026-present</span><p>Leading the development of an on-campus evangelism initiative, mentoring students, and coordinating large events through team collaboration.</p></div><div><strong>Teaching Assistant</strong><span>Celina High School · August 2022-May 2024</span><p>Supported AP Computer Science I &amp; II instruction in object-oriented design and problem-solving, helping students debug code and understand complex topics.</p></div></div></div></section>
      <section className="skills-band"><div className="shell skills-grid"><div><p className="eyebrow">The toolkit</p><h2>Built to understand<br /><em>the whole threat surface.</em></h2></div><div className="skill-columns"><div><span>Security focus</span><p>Cybersecurity<br />Post-quantum encryption<br />Lattice cryptography<br />ABE / IBE</p></div><div><span>Languages &amp; web</span><p>Python / C / C++<br />Java / JavaScript<br />HTML / CSS<br />React / Vite / Flutter</p></div><div><span>Systems &amp; tools</span><p>Dart / Assembly<br />Git / Embedded systems<br />Quartus / KiCad / Keil<br />Full-stack development</p></div></div></div></section>
      <section className="contact shell" id="contact"><p className="eyebrow">Have a problem worth solving?</p><h2>Let’s talk<br /><em>about the next one.</em></h2><div className="contact-row"><a className="button button-primary" href="mailto:Jbbennettwork@gmail.com">Start a conversation <span>↗</span></a><span>College Station, Texas<br /><a href="tel:2147944678">(214) 794-4678</a></span></div></section><footer className="footer shell"><span>© 2026 Josh Bennett</span><span>Designed &amp; built with intent.</span><a href="#top">Back to top ↑</a></footer>
    </main>
  )
}

export default App
